<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => 'CSV',
    'Download {name}' => 'Lataa {name}',
    'Excel' => 'Excel',
    'MS CSV' => 'MS CSV',
    'Administration' => 'Ylläpito',
    'Are you sure you want to delete this item?' => 'Haluatko varmasti poistaa tämän?',
    'Choose {name}' => 'Valitse {name}',
    'Content' => 'Sisältö',
    'Could not delete {name}.' => 'Kohdetta "{name}" ei voitu poistaa.',
    'Could not upload file.' => 'Tiedostoa ei voitu tallentaa.',
    'Create {name}' => 'Luo uusi {name}',
    'Delete' => 'Poista',
    'Delete file' => 'Poista tiedosto',
    'Delete image' => 'Poista kuva',
    'Download file' => 'Lataa tiedosto',
    'List {name}' => 'Listaa {name}',
    'Login' => 'Kirjaudu sisään',
    'Logout ({username})' => 'Kirjaudu ulos ({username})',
    'Preview image' => 'Kuvan esikatselu',
    'Save' => 'Tallenna',
    'Save and add another' => 'Tallenna ja lisää uusi',
    'Save and continue editing' => 'Tallenna ja jatka muokkausta',
    'Update' => 'Päivitä',
    'Update {name}' => 'Päivitä {name}',
    '{name} has been created.' => '{name} on luotu.',
    '{name} has been deleted.' => '{name} on poistettu.',
    '{name} has been updated.' => '{name} on päivitetty.',
];
